### ISSUE TITLE
The mask property is not working correctly with the latest starling master (from github)

### ISSUE THREAD

**Issue by Fraggle** [CatalystApps/StarlingGAFPlayer#25]
I cant pinpoint exactly but i'm sure you'll find out quicker than me :)

Thanks :)

Seb

**Comment by Fraggle** [comment]
This commit broke it https://github.com/Gamua/Starling-Framework/commit/9462e87d755fc7548242271162c8c0061837e8bc

**Comment by ivanavdieienko** [comment]
Hi.
The official release of Starling 1.6.1. didn't came yet. So you can use 1.6 version (without masks) or modify the StarlingGAFPlayer sources this way:
1) override mask setter in starling/extensions/pixelmask/PixelMaskDisplayObject.as
2) override mask getter in com/catalystapps/gaf/display/GAFPixelMaskDisplayObject.as
3) replace the starling.swc with Starling 1.6.1 library.

**Comment by ivanavdieienko** [comment]
Hi.
We will modify GAF library after the official release of Starling 1.6.1. So everyone can use the latest GAF library with the latest official Starling version 1.6. If you need to use GAF Library with Starling 1.6.1 make the following changes in sources of the GAF library: 
1) override mask setter in starling/extensions/pixelmask/PixelMaskDisplayObject.as
2) override mask getter in com/catalystapps/gaf/display/GAFPixelMaskDisplayObject.as

**Comment by Fraggle** [comment]
Actually, this commit is broke the masking feature more than just overriding the getter and setter..

**Comment by ivanavdieienko** [comment]
You're right. It took us some time to reproduce an actual issue. So the problem occured in DisplayObjectContainer.render() method. It checks for "mask" property in all children and then tryes to draw it by itself.

As the result we renamed mask property to pixelMask in PixelMaskDisplayObject and GafPixelMaskDisplayObject classes. It fixed the bug and the conflict of names.

**Comment by Fraggle** [comment]
Thanks !
