### ISSUE TITLE
Reduce objects creations

### ISSUE THREAD

**Issue by Fraggle** [CatalystApps/StarlingGAFPlayer#28]
Hello again,

(I do a lot of scout investigations)
I noticed that you create quite a few objects because of GAFFilter resetBlurFilter() and resetColorMatrixFilter() reassigning new Vector instead of just setting the values to whatever their defaults are. It's a bit more code but much less overhead and memory.
example:
```
mOffsets = new <Number>[0, 0, 0, 0];
```
becomes
```
mOffsets[0] = mOffsets[1] = mOffsets[2] = mOffsets[3] = 0;
```
and so on...

Thanks for reading me.

**Comment by ivanavdieienko** [comment]
done
