### ISSUE TITLE
Feature request: Add support for rotated subtextures.

### ISSUE THREAD

**Issue by LordXaoca** [CatalystApps/StarlingGAFPlayer#30]
Hi, starting from Starling 1.5 it supports rotated subtexures, it would be nice if your library supports it too.
Proof: http://gamua.com/blog/2014/05/starling-15/

**Comment by BregoXX** [comment]
good feature
+1

**Comment by dkruglik** [comment]
+1

**Comment by mitvad** [comment]
Guys, we already are working on this function in GAF Converter and in libraries. It will be available very soon. Stay tuned!

**Comment by LordXaoca** [comment]
Thank you!

**Comment by ivanavdieienko** [comment]
We support rotated subtextures since 5.0 release. More info in our blog http://gafmedia.com/blog/gaf-converter-version-5-0
