### ISSUE TITLE
Storing textures in RAM

### ISSUE THREAD

**Issue by ricofegh** [CatalystApps/StarlingGAFPlayer#31]
Hi.
I load a lot of GAF animations while my application is being loaded. Every animation consumes some amount of the texture memory, which is limited in Starling by only 128 mb. In my case, textures take 60 Mb of the texture memory, which is almost half of that amount. That's why I want to unload textures from video memory and keep them in RAM until I need to display GAFMovieClip that uses them. Before there was an option ZipToGAFAssetConverter.keepImagesInRAM, which gave me ability to unload timelines from video memory and load them again when it's needed directly from the RAM. Now this option is removed. The only thing I can do now is to load timeline from GAF zip files every time, but this operation is very slow and it has no sense to do it more than one time while application is running.
Please, recommend me approach for managing my video memory consumption. Thank you.

**Comment by ivanavdieienko** [comment]
Hi. Please, use Starling.handleLostContext = true instead of ZipToGAFAssetConverter.keepImagesInRAM.
