### ISSUE TITLE
Filters in the binary format

### ISSUE THREAD

**Issue by bp74** [CatalystApps/StarlingGAFPlayer#37]
Hi guys,

I'm working on a runtime for StageXL/HTML5 and i use the AS3 code as a reference for the implementation. Currently i'm working on the filters and i wonder if you left out a few filters in the AS3 code. Looking at the code it seems there are undefinied filters:

    //BinGAFAssetConfigConverter.as

    private static const FILTER_DROP_SHADOW: uint = 0;
    private static const FILTER_BLUR: uint = 1;
    private static const FILTER_GLOW: uint = 2;
    private static const FILTER_COLOR_MATRIX: uint = 6;

Filters 3,4,5 are not defined, so i wonder what those filters are and how they look like in the binary format. The StageXL runtime could probably support all or at least some of the other filters.

https://github.com/bp74/StageXL_GAF
http://www.stagexl.org/show/gaf/skeleton/example.html
http://www.stagexl.org/show/gaf/fireman/example.html

**Comment by mitvad** [comment]
Hi,

This is a full list of the filters that GAF Converter reads from SWF file and writes in GAF format (so there is no "hidden" filters that you can't find in the Starling GAF library). As you see some filters are not supported (we only read filters that we can implement in all supported libraries).

Full list of filters from SWF format:
0 = DropShadowFilter 
1 = BlurFilter
2 = GlowFilter
3 = BevelFilter
4 = GradientGlowFilter 
5 = ConvolutionFilter
6 = ColorMatrixFilter
7 = GradientBevelFilter

For now there is no plan to support all filters from SWF format. Only existent filters.

**Comment by bp74** [comment]
Thanks for your reply. To be clear, those filters (3,4,5,7) are not supported by the AS3/Starling runtime or by the GAFConverter? My understanding is that those filters are not supported by the AS3/Starling runtime but GAFConverter does export those filters, right?

**Comment by mitvad** [comment]
No. Filters 3,4,5,7 are not supported by GAF Converter too.

**Comment by bp74** [comment]
Oh i see, after reading your answer again i understand what you mean :) sorry about that.
So i don't need to worry about those other filters right now. Thanks again!
